server:
  port: 8080
dubbo:
  application:
    logger: slf4j
    name: HospitalHealthDocumentApplication
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: tri
    port: 50051
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
    username: root
    password: lmx175586
    driver-class-name: com.mysql.cj.jdbc.Driver
