server:
  port: 8080
dubbo:
  application:
    logger: slf4j
    name: HospitalHealthDocumentApplication
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: tri
    port: 50051
