server:
  port: 8081
spring:
  application:
    name: hospital-discharge-service
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
