spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: hhy20040619
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

dubbo:
  application:
    logger: slf4j
    name: HospitalEstimateApplication
  protocol:
    name: tri
    port: 50051
  registry:
    address: N/A
server:
  port: 8084

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.uutrunk.hospitalestimate.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

