server:
  port: 8082

spring:
  application:
    name: medical-prescription-service  # 修改服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_db
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 语句
  global-config:
    db-config:
      id-type: auto  # 主键类型，根据需要调整
