server:
  port: 8083
dubbo:
  application:
    logger: slf4j
    name: HospitalOrdermanagementApplication
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: tri
    port: 50051
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lmx175586
  cloud:
    ai:
      tongyi:
        api-key: sk-e1add1a99a154155b133d250a33f875c
