server:
  port: 8080
dubbo:
  application:
    logger: slf4j
    name: HospitalOrdermanagementApplication
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  protocol:
    name: tri
    port: 50051
